# Generated by Django 3.2.6 on 2021-08-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'pokemons'},
        ),
    ]
